POST http://localhost:8080/api
Content-Type: application/json

{
  "name": "First class",
  "startDate": "2021-06-01",
  "endDate": "2021-08-02"

}

###
GET http://localhost:8080/api
Accept: application/json

###
GET http://localhost:8080/api/5
Accept: application/json

###

POST http://localhost:8080/api/trainingclasses/1/registrations
Content-Type: application/json

{
  "studentId": 2

}

###

POST http://localhost:8080/api/trainingclasses/1/registrations
Content-Type: application/json

{
  "studentId": 1

}

###

POST http://localhost:8080/api/trainingclasses/2/registrations
Content-Type: application/json

{
  "studentId": 2

}

###

POST http://localhost:8080/api/trainingclasses/2/registrations
Content-Type: application/json

{
  "studentId": 3

}


###

GET http://localhost:8080/api/trainingclasses/2/registrations
Accept: application/json

###

GET http://localhost:8080/api/students/2/registrations
Accept: application/json

###